pkg/logcutter/logcutter_test.go
pkg/store/logfile_test.go

[logging] Fix unit tests

---

cmd/server/run.go
pkg/executor/executor.go
pkg/werft/github.go
pkg/werft/werft.go

Once a job finishes we start a "cleanup job" which removes the workspace content from the node.

[server] Cleanup workspace content after a job finishes

---

pkg/webui/src/App.tsx
pkg/webui/src/JobView.tsx

Default to the result view for successfully finished jobs with at least one result

[webui] Default to results view for successful finished jobs

---

cmd/client/job-get.go
cmd/client/job-logs.go
cmd/client/job.go
cmd/client/run.go

[cli] Use local context in `werft job get`

---

pkg/webui/src/JobList.tsx

[webui] Add links to repo and ref in the job overview

---

cmd/client/run.go

Signed-off-by: Sean Hellum <seanhellum45@gmail.com>

alias `werft job run` to `werft run`

---

pkg/webui/src/JobList.tsx

With this commit the search filter is applied to the job subscription event stream as well.
_Feel free to improve this according to your needs._
Fixes #39.

Add filter to job subscription request

---

cmd/client/init-job.go

[cli] Correct indentation in new job template

---

README.md

Mention contributors

---

pkg/werft/service.go
pkg/werft/service_test.go

[server] Prevent allow invalid pod names

---

pkg/werft/github.go
pkg/werft/service.go

[server] Resolve to correct revision when resolving branches

---

pkg/webui/src/App.tsx
pkg/webui/src/BranchList.tsx
pkg/webui/src/JobList.tsx
pkg/webui/src/JobTree.tsx

This is an experiment. Adds an experimental new view: branches.
This first draft just takes the last 200 jobs and sorts them by branches. This is not meant to be the final version of this feature, but a start.

[web-ui] Add branches view

---

pkg/webui/src/components/LogView.tsx

[web-ui] Add permalinks to unfolded log chunks

---

pkg/webui/src/components/ResultView.tsx

Fixes csweichel/werft#67

---

pkg/webui/src/JobView.tsx
pkg/webui/src/StartJob.tsx

By:
- ~~renaming `Finished` to `Duration`~~
- adding helpful tooltips to `Ref` and `Revision` in the UI

Clarify UI fields like Ref and Revision

---

README.md

Add table of contents. Add Annotations section and describe how to pass annotations.

Add TOC and annotations section

---

.gitpod.yml

Removed no longer supported options from .gitpod.yml

[gitpod] fixed .gitpod.yml

---

plugins/cron/main.go

[cron] fixed a race

---

.gitpod.yml
pkg/werft/content.go
werft.theia-workspace

Fix content sideloading

---

pkg/webui/src/JobView.tsx

Rename "Finished" field to Duration

---

pkg/store/logfile.go

Don't keep the log while removing old files.
might help with #139

[GC] improve log file GC performance

---

cmd/client/root.go

Fixes #150 
Allows the use of a TLS dial mode using system certificates

Add flag for using TLS dial mode in the CLI

---

plugins/github-integration/main.go

Fixes https://github.com/gitpod-io/ops/issues/2964

Process PR Opened event

---

pkg/werft/service.go

Fix # in branch names

---

pkg/plugin/client/client.go

fixes 168
not very happy with this, but it's really unclear why this happens

Add workaround for gRPC issues

---

plugins/github-integration/main.go

Fixes https://github.com/gitpod-io/ops/issues/2964

Only compare annotations on edit
